### PR TITLE
Nowa komenda i force jak sie pali

### PR DESCRIPTION
**Pull request by rpodwika**

### CODE REVIEW

**Comment by jakubnabrdalik** [comment]
Looks good, but can you please write git comments in English?
Otherwise you make it hard for others to navigate or read git log.

**Comment by rpodwika** [comment]
yes sure

**Comment by rpodwika** [comment]
Could you make rebase to master and change commit message? It's hard to me to do it by WEB and I can't download it onto my company's computer ;/

**Comment by jakubnabrdalik** [comment]
Ok, no worries

**Comment by jakubnabrdalik** [comment]
Done

**Pull request closed without merging**
